### ISSUE TITLE
Update link to Endpoints

### ISSUE THREAD

**Issue by juanlp** [lgoodridge/serverless-chat#3]
Hello

Thank you for the tutorial and the gitcode. 

I found your code here is a bit different from the tutorial, I wonder where i should update the wss endpoint? and https endpoint?

Many thanks.

**Comment by lgoodridge** [comment]
Hello! The `serverless.yml` file controls the backend endpoints, which the frontend connects to via the `setupWebsocket` method in `custom.js`

If you're following the tutorial, the endpoint URL is passed directly to the `ReconnectingWebSocket` constructor, but I updated the code on github to get it from an environment variable, so it can be easily configured. You can quickly set this variable with: `export WEBSOCKET_ENDPOINT=<your_endpoint>`.

If this didn't answer your question, let me know what part of the tutorial you're on, and I can provide more specific pointers.
