### ISSUE TITLE
Chatroom implementation

### ISSUE THREAD

**Issue by kronos-999** [lgoodridge/serverless-chat#5]
Hey,
could you please provide a quick working example of chatroom-based messaging?

I cannot seem to get it work

Thanks!

**Comment by lgoodridge** [comment]
Adding "rooms" (as in, multiple chats with separate conversations) is a bit outside the scope of the tutorial and this example app, although the backend was designed knowing that would be a natural extension. Is there something in particular you're struggling to get working?

**Comment by kronos-999** [comment]
I think i got it working, thanks! I was able to create a GSI and added a "chatroom" to the connection table to send messages only to those that are in the connection table with the right chatroom they specified within jwt.
Maybe you could share some info about how to do it since you mentioned in your article that adding chatrooms was just a matter of adding the chatroom to the body of the request :)
